"""v3 — High-spec composite augmented with per-beat QRS width features.

QRS width is *negative* evidence for AFib (PVC = wide). We add width
features both to the rule pool (so greedy can pick "AFib if wide_frac ≤
X") and as a global VETO gate ("predict AFib only when wide-QRS evidence
is below threshold").

Two configurations compared:
  (A) extended OR-pool: width features compete with RR features as
      positive-AFib rules (via ≤ direction)
  (B) RR composite + width veto: keep the prior 9-rule RR composite,
      then post-veto windows whose max QRS width is wide.

Cache must have widths_ms; if missing, regenerated by build_rr_cache.
"""
from __future__ import annotations

import os
from pathlib import Path
import warnings

import numpy as np
import pandas as pd

from scripts.afib_deadband_sweep import (
    FEATURES, T_GRID, build_rr_cache,
)

warnings.filterwarnings("ignore", category=RuntimeWarning)
warnings.filterwarnings("ignore", message="An input array is constant")
os.environ.setdefault(
    "OPENECG_LYDUS_DIR", "G:/Shared drives/datasets/ecg/lydus_ecg"
)

PER_RULE_SPEC_FLOOR = 0.95
GLOBAL_FP_BUDGET = 0.05


# --------------------------------------------------- width-derived features --


def qrsw_median(rr, w, T=0):
    if len(w) == 0:
        return 0.0
    return float(np.median(w))


def qrsw_max(rr, w, T=0):
    if len(w) == 0:
        return 0.0
    return float(np.max(w))


def qrsw_p90(rr, w, T=0):
    if len(w) == 0:
        return 0.0
    return float(np.percentile(w, 90))


def qrsw_cv(rr, w, T=0):
    if len(w) < 2 or np.mean(w) < 1e-6:
        return 0.0
    return float(np.std(w) / np.mean(w))


def qrsw_iqr(rr, w, T=0):
    if len(w) < 4:
        return 0.0
    q1, q3 = np.percentile(w, [25, 75])
    return float(q3 - q1)


def wide_frac(rr, w, T=120):
    """Fraction of beats wider than T ms (default 120 = clinical BBB cutoff)."""
    if len(w) == 0:
        return 0.0
    return float(np.mean(w >= T))


# These take (rr, w, T) — second positional is widths array, not RR.
WIDTH_FEATURES = {
    "qrsw_median": qrsw_median,
    "qrsw_max":    qrsw_max,
    "qrsw_p90":    qrsw_p90,
    "qrsw_cv":     qrsw_cv,
    "qrsw_iqr":    qrsw_iqr,
    "wide_frac":   wide_frac,
}

# Width-feature deadband interpretation = wide-QRS threshold for wide_frac;
# 0 (i.e., no threshold modification) for others.
WIDTH_T_GRID = {
    "qrsw_median": [0],
    "qrsw_max":    [0],
    "qrsw_p90":    [0],
    "qrsw_cv":     [0],
    "qrsw_iqr":    [0],
    "wide_frac":   [100, 110, 120, 130, 140],   # threshold in ms
}


def enumerate_rules(scores: np.ndarray, y: np.ndarray, name: str, T: int,
                    spec_floor: float):
    out = []
    for sign in ("≥", "≤"):
        s_use = scores if sign == "≥" else -scores
        for t in np.unique(s_use):
            pred = s_use >= t
            tp = pred & (y == 1)
            fp = pred & (y == 0)
            n_pos = (y == 1).sum()
            n_neg = (y == 0).sum()
            sens = tp.sum() / max(1, n_pos)
            spec = 1 - fp.sum() / max(1, n_neg)
            if spec < spec_floor or tp.sum() == 0:
                continue
            raw_thr = float(t if sign == "≥" else -t)
            out.append(dict(
                name=name, T=int(T), sign=sign, thr=raw_thr,
                tp_mask=tp, fp_mask=fp,
                sens=float(sens), spec=float(spec),
                n_tp=int(tp.sum()), n_fp=int(fp.sum()),
            ))
    return out


def greedy_union(rule_pool, y, fp_budget, verbose=True):
    n_pos = (y == 1).sum()
    n_neg = (y == 0).sum()
    chosen = []
    used_names = set()
    union_tp = np.zeros(len(y), dtype=bool)
    union_fp = np.zeros(len(y), dtype=bool)
    while True:
        best_score = 0.0
        best_rule = None
        for r in rule_pool:
            if (r["name"], r["T"]) in used_names:
                continue
            new_tp = int((r["tp_mask"] & ~union_tp).sum())
            new_fp = int((r["fp_mask"] & ~union_fp).sum())
            if new_tp == 0:
                continue
            if (union_fp | r["fp_mask"]).sum() > fp_budget:
                continue
            score = new_tp / (1.0 + new_fp)
            if score > best_score:
                best_score = score
                best_rule = r
                best_new_tp = new_tp
                best_new_fp = new_fp
        if best_rule is None:
            break
        chosen.append(best_rule)
        used_names.add((best_rule["name"], best_rule["T"]))
        union_tp |= best_rule["tp_mask"]
        union_fp |= best_rule["fp_mask"]
        if verbose:
            sens = union_tp.sum() / n_pos
            spec = 1 - union_fp.sum() / n_neg
            print(f"   + [{best_rule['name']:<14}] T={best_rule['T']:>3} "
                  f"{best_rule['sign']} {best_rule['thr']:.4g}  "
                  f"+{best_new_tp} TP / +{best_new_fp} FP  "
                  f"→ sens={sens:.3f} spec={spec:.3f} "
                  f"FP={int(union_fp.sum())}/{fp_budget}")
    return chosen, union_tp, union_fp


def main():
    cache_path = Path("logs/afib_rr_cache.parquet")
    df = build_rr_cache(cache_path)
    df = df[df["rr_ms"].apply(lambda x: len(x) >= 4)].reset_index(drop=True)
    rr_arrays = [np.asarray(r, dtype=np.float64) for r in df["rr_ms"]]
    w_arrays  = [np.asarray(w, dtype=np.float64) for w in df["widths_ms"]]
    y = df["y"].values
    cls = df["class"].values
    n_pos = int((y == 1).sum())
    n_neg = int((y == 0).sum())
    fp_budget = int(np.floor(GLOBAL_FP_BUDGET * n_neg))
    print(f"## Setup: n={len(y)}  pos={n_pos}  neg={n_neg}  "
          f"per-rule spec≥{PER_RULE_SPEC_FLOOR}  global FP budget={fp_budget}")

    # ---- Step 1 — QRS width distribution per class --------------------------
    print("\n## Step 1 — QRS-width distribution per class (ms)")
    print(f"  {'class':<6} {'median':>8} {'p90':>8} {'max':>8} "
          f"{'cv':>8} {'wide@120':>10}")
    for c in ["AFib", "NSR", "PVC", "AVB2", "AVB3"]:
        idx = np.where(cls == c)[0]
        if len(idx) == 0:
            continue
        med = np.array([np.median(w_arrays[i]) for i in idx])
        p90 = np.array([np.percentile(w_arrays[i], 90) if len(w_arrays[i]) else 0
                        for i in idx])
        mx  = np.array([np.max(w_arrays[i]) if len(w_arrays[i]) else 0
                        for i in idx])
        cv  = np.array([qrsw_cv(None, w_arrays[i]) for i in idx])
        wf  = np.array([wide_frac(None, w_arrays[i], 120) for i in idx])
        print(f"  {c:<6} {np.median(med):>8.1f} {np.median(p90):>8.1f} "
              f"{np.median(mx):>8.1f} {np.median(cv):>8.3f} "
              f"{np.median(wf):>10.3f}")

    # ---- Step 2 — AUROC of each width feature -----------------------------
    print("\n## Step 2 — AUROC of width features (AFib=1)")
    from sklearn.metrics import roc_auc_score, roc_curve
    print(f"  {'feature':<14} {'AUROC':>8}  rule")
    for name, fn in WIDTH_FEATURES.items():
        for T in WIDTH_T_GRID[name]:
            scores = np.array([fn(None, w, T) for w in w_arrays])
            s = np.nan_to_num(scores, nan=float(np.nanmedian(scores)))
            auc_hi = roc_auc_score(y, s)
            if auc_hi >= 0.5:
                auc, sign, s_use = auc_hi, "≥", s
            else:
                auc, sign, s_use = 1 - auc_hi, "≤", -s
            fpr, tpr, thr = roc_curve(y, s_use)
            k = int(np.argmax(tpr - fpr))
            raw_thr = -thr[k] if sign == "≤" else thr[k]
            sens = float(tpr[k])
            spec = float(1 - fpr[k])
            tag = f"{name}@T={T}" if T else name
            print(f"  {tag:<14} {auc:>8.3f}  AFib if {name} {sign} {raw_thr:.3g}  "
                  f"sens={sens:.2f} spec={spec:.2f}")

    # ---- Step 3 — Build extended rule pool (RR + width features) ------------
    print("\n## Step 3 — Building extended rule pool (RR + width)")
    pool: list[dict] = []
    # RR features
    for name, fn in FEATURES.items():
        for T in T_GRID:
            scores = np.array([fn(rr, T) for rr in rr_arrays])
            pool.extend(enumerate_rules(scores, y, name, T, PER_RULE_SPEC_FLOOR))
    # Width features
    for name, fn in WIDTH_FEATURES.items():
        for T in WIDTH_T_GRID[name]:
            scores = np.array([fn(None, w, T) for w in w_arrays])
            pool.extend(enumerate_rules(scores, y, name, T, PER_RULE_SPEC_FLOOR))
    pool.sort(key=lambda r: (-r["n_tp"], r["n_fp"]))
    print(f"   pool size: {len(pool)}")

    # ---- Step 4A — Greedy union with extended pool --------------------------
    print(f"\n## Step 4A — Greedy union (RR + width pool) ≤ {fp_budget} FP")
    chosen_A, tp_A, fp_A = greedy_union(pool, y, fp_budget)

    # ---- Step 4B — RR-only composite + global wide-QRS veto -----------------
    print(f"\n## Step 4B — RR composite + wide-QRS veto")
    rr_only_pool = [r for r in pool if r["name"] not in WIDTH_FEATURES]
    chosen_B0, tp_B0, fp_B0 = greedy_union(rr_only_pool, y, fp_budget, verbose=False)
    sens_b0 = tp_B0.sum() / n_pos
    spec_b0 = 1 - fp_B0.sum() / n_neg
    print(f"   RR-only baseline: {len(chosen_B0)} rules  sens={sens_b0:.3f}  "
          f"spec={spec_b0:.3f}  FP={int(fp_B0.sum())}")
    # Now apply wide-QRS veto: predict AFib only if max width < V threshold
    # AND any RR rule fires.
    print(f"   Sweeping wide-QRS veto threshold V:")
    print(f"   {'V (ms)':<8} {'sens':>8} {'spec':>8} {'PVC FPR':>10} "
          f"{'AVB3 FPR':>10} {'NSR FPR':>10}")
    for V in (90, 100, 110, 115, 120, 130, 140):
        max_w = np.array([float(np.max(w)) if len(w) else 0.0 for w in w_arrays])
        veto = max_w >= V
        pred = (tp_B0 | fp_B0) & ~veto
        tp = pred & (y == 1)
        fp = pred & (y == 0)
        sens = tp.sum() / max(1, n_pos)
        spec = 1 - fp.sum() / max(1, n_neg)
        pvc_fpr = (pred & (cls == "PVC")).sum() / max(1, (cls == "PVC").sum())
        avb3_fpr = (pred & (cls == "AVB3")).sum() / max(1, (cls == "AVB3").sum())
        nsr_fpr = (pred & (cls == "NSR")).sum() / max(1, (cls == "NSR").sum())
        print(f"   {V:<8} {sens:>8.3f} {spec:>8.3f} {pvc_fpr:>10.3f} "
              f"{avb3_fpr:>10.3f} {nsr_fpr:>10.3f}")

    # Pick the best veto threshold by maximising (sens × spec) with spec ≥ 0.95
    print(f"\n   Choosing best V: maximise sens with global spec ≥ 0.95")
    best_V = None
    best_sens = -1
    for V in (90, 100, 110, 115, 120, 130, 140):
        max_w = np.array([float(np.max(w)) if len(w) else 0.0 for w in w_arrays])
        veto = max_w >= V
        pred = (tp_B0 | fp_B0) & ~veto
        tp = pred & (y == 1)
        fp = pred & (y == 0)
        sens = tp.sum() / max(1, n_pos)
        spec = 1 - fp.sum() / max(1, n_neg)
        if spec >= 0.95 and sens > best_sens:
            best_sens = sens
            best_V = V
    print(f"   best V = {best_V} ms")

    # ---- Final summary --------------------------------------------------------
    print("\n## Final comparison")
    sens_A = tp_A.sum() / n_pos
    spec_A = 1 - fp_A.sum() / n_neg
    print(f"  (A) extended OR-pool      : {len(chosen_A)} rules  "
          f"sens={sens_A:.3f}  spec={spec_A:.3f}")
    if best_V is not None:
        max_w = np.array([float(np.max(w)) if len(w) else 0.0 for w in w_arrays])
        veto = max_w >= best_V
        pred = (tp_B0 | fp_B0) & ~veto
        tp = pred & (y == 1)
        fp = pred & (y == 0)
        sens_b = tp.sum() / n_pos
        spec_b = 1 - fp.sum() / n_neg
        print(f"  (B) RR composite + V={best_V}ms veto: "
              f"sens={sens_b:.3f}  spec={spec_b:.3f}")
        print("\n   per-class predicted-as-AFib rate (B):")
        for c in ["AFib", "NSR", "PVC", "AVB2", "AVB3"]:
            mask = cls == c
            if mask.any():
                rate = pred[mask].mean() * 100
                n_caught = int(pred[mask].sum())
                print(f"     {c:>5}: {rate:5.1f}%  ({n_caught}/{mask.sum()})")

    # Show rules for (A)
    print("\n## Final composite (A) — extended OR rules")
    print("AFib  ⟺  ANY of:")
    for i, r in enumerate(chosen_A, 1):
        unit = "ms" if r["name"].startswith(("qrsw_", "wide_", "rmssd")) else ""
        deadband = f"  [T={r['T']}]" if r["T"] != 0 else ""
        print(f"  R{i}:  {r['name']} {r['sign']} {r['thr']:.4g}{unit}{deadband}  "
              f"(TP={r['n_tp']}, FP={r['n_fp']})")

    print("\n## Final composite (B) — RR rules + width veto")
    print(f"AFib  ⟺  (ANY of {len(chosen_B0)} RR rules)  AND  max(qrs_width) < {best_V} ms")
    for i, r in enumerate(chosen_B0, 1):
        deadband = f"  [T={r['T']}]" if r["T"] != 0 else ""
        print(f"  R{i}:  {r['name']} {r['sign']} {r['thr']:.4g}{deadband}")


if __name__ == "__main__":
    main()
